### ISSUE TITLE
[功能请求]RTSP seek

### ISSUE THREAD

**Issue by pubpy2015** [xia-chu/ZLMediaKit#827]
**描述该功能的用处，可以提供相关资料描述该功能**

Using MediaServer connect to DVR/NVR to playback video through rtsp url. 
ex: 
rtsp://admin:admin@10.44.200.8:554/cam/playback?channel=1&starttime=2012_09_15_12_37_05&endtime=2012_09_15_18_34_14

**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**

can not seek.

**描述你期望实现该功能的方式和最终效果**

support seek as VLC

**Comment by xia-chu** [comment]
This should not be the function of the live stream server,
If we pull and proxy a stream and many users watch it at the same time, one of the users seek the video, what will happened to other users?

**Comment by pubpy2015** [comment]
Hi,

incase of NVR, with same rtsp url, if one user seek, other user not affect.

![image](https://user-images.githubusercontent.com/59004953/115722416-2cb82c00-a3a9-11eb-8225-d2fb0c99f917.png)

**Comment by xia-chu** [comment]
The RTSP server in the camera is completely different from ZLM,
Playback in the camera is to read the file directly, and the file can be seeked directly. In fact, ZLM also supports this method. However, if the RTSP stream is proxy pulled by ZLM, it cannot be seeked for other players at the same time, because the stream of the pull rtsp stream is shared with multiple players. And at present if ZLM received one seek request, ZLM will not send seek request to amera.

**Comment by pubpy2015** [comment]
Thanks.
